package com.rithsagea.skyblock.api.datatypes;

public enum DragonEquipment implements ItemType {
	
	CRYSTAL_FRAGMENT,
	CRYSTAL_HELMET,
	CRYSTAL_CHESTPLATE,
	CRYSTAL_LEGGINGS,
	CRYSTAL_BOOTS,
	
	OLD_FRAGMENT,
	OLD_DRAGON_HELMET,
	OLD_DRAGON_CHESTPLATE,
	OLD_DRAGON_LEGGINGS,
	OLD_DRAGON_BOOTS,
	
	PROTECTOR_FRAGMENT,
	PROTECTOR_DRAGON_HELMET,
	PROTECTOR_DRAGON_CHESTPLATE,
	PROTECTOR_DRAGON_LEGGINGS,
	PROTECTOR_DRAGON_BOOTS,
	
	STRONG_FRAGMENT,
	STRONG_DRAGON_HELMET,
	STRONG_DRAGON_CHESTPLATE,
	STRONG_DRAGON_LEGGINGS,
	STRONG_DRAGON_BOOTS,
	
	SUPERIOR_FRAGMENT,
	SUPERIOR_DRAGON_HELMET,
	SUPERIOR_DRAGON_CHESTPLATE,
	SUPERIOR_DRAGON_LEGGINGS,
	SUPERIOR_DRAGON_BOOTS,
	
	UNSTABLE_FRAGMENT,
	UNSTABLE_DRAGON_HELMET,
	UNSTABLE_DRAGON_CHESTPLATE,
	UNSTABLE_DRAGON_LEGGINGS,
	UNSTABLE_DRAGON_BOOTS,
	
	WISE_FRAGMENT,
	WISE_DRAGON_HELMET,
	WISE_DRAGON_CHESTPLATE,
	WISE_DRAGON_LEGGINGS,
	WISE_DRAGON_BOOTS,
	
	YOUNG_FRAGMENT,
	YOUNG_DRAGON_HELMET,
	YOUNG_DRAGON_CHESTPLATE,
	YOUNG_DRAGON_LEGGINGS,
	YOUNG_DRAGON_BOOTS;
}
